exports.paginaInicial = function (d) {
    return `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
        <title>Página Inicial</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-blue">
                <h1>Compositores famosos</h1>
            </header>
            <div class="w3-container">
                <ul>
                    <li><a href="/compositores">Compositores</a></li>
                    <li><a href="/periodos">Períodos</a></li>
                </ul>
            </div>
            <footer class="w3-container w3-blue">
                <h5>Generated by RPCW2023 in ${d}</h5>
            </footer>
        </div>
    </body>
    </html>
    `
}

exports.listaCompositores = function (list, d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
        <title>Lista de Compositores</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-blue">
                <h1>Lista de Compositores</h1>
                <a href="/compositores/add">Novo Compositor</a>
            </header>
    
            <div class="w3-container">
                <table class="w3-table-all">
                    <tr>
                        <th>Id</th><th>Nome</th><th>Ações</th>
                    </tr>
                
    `
    for (let i = 0; i < list.length; i++) {
        pagHTML += `
        <tr>
            <td>${list[i].id}</td>
            <td>
                <a href="/compositores/${list[i].id}">
                    ${list[i].nome}
                </a>
            </td>
            <td>
                [<a href="/compositores/edit/${list[i].id}">Editar</a>][<a href="/compositores/delete/${list[i].id}">Apagar</a>]
            </td>
        </tr>
        `
    }

    pagHTML += `
    </table>
    </div>
        <footer class="w3-container w3-blue">
            <h5>Generated by RPCW2023 in ${d} - [<a href="/">Voltar à página inicial</a>]</h5>
        </footer>
    </div>
    </body>
    </html>
    `

    return pagHTML
}

exports.paginaCompositor = function (compositor, d) {
    return `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
        <title>Compositor: ${compositor.nome}</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-blue">
                <h1>Compositor: ${compositor.nome}</h1>
            </header>
            <div class="w3-container">
                <p>ID: ${compositor.id}</p>
                <p>Biografia: ${compositor.bio}</p>
                <p>Data de nascimento: ${compositor.dataNasc}</p>
                <p>Data de óbito: ${compositor.dataObito}</p>
                <p>Período: ${compositor.periodo}</p>
            </div>
            <footer class="w3-container w3-blue">
                <h5>Generated by RPCW2023 in ${d} - [<a href="/compositores">Voltar à lista de compositores</a>]</h5>
            </footer>
        </div>
    </body>
    </html>
    `
}

exports.editarCompositor = function (compositor, d) {
    return `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
        <title>Editar ${compositor.nome}</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-blue">
                <h1>Editar ${compositor.nome}</h1>
            </header>
            <div class="w3-container">
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Dados para editar</legend>
                        <label>ID</label>
                        <input class="w3-input w3-round" type="text" name="id" value="${compositor.id}"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${compositor.nome}"/>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${compositor.periodo}"/>
                        <label>Biografia</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${compositor.bio}"/>
                        <label>Data de nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc" value="${compositor.dataNasc}"/>
                        <label>Data de óbito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito" value="${compositor.dataObito}"/>
                    <fieldset/>
                    <br>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Registar Alterações</button>
                </form>
            </div>
            <footer class="w3-container w3-blue">
                <h5>Generated by RPCW2023 in ${d} - [<a href="/compositores">Voltar à lista de compositores</a>] </h5>
            </footer>
        </div>
    </body>
    </html>
    `
}

exports.adicionarCompositor = function (d) {
    return `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
        <title>Novo Compositor</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-blue">
                <h1>Novo Compositor</h1>
            </header>
            <div class="w3-container">
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Dados do novo Compositor</legend>
                        <label>ID</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                        <label>Biografia</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        <label>Data de nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc"/>
                        <label>Data de óbito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito"/>
                    <fieldset/>
                    <br>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Registar novo Compositor</button>
                </form>
            </div>
            <footer class="w3-container w3-blue">
                <h5>Generated by RPCW2023 in ${d} - [<a href="/compositores">Voltar à lista de compositores</a>]</h5>
            </footer>
        </div>
    </body>
    </html>
    `
}

exports.listaPeriodos = function (list, d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
        <title>Lista de Períodos</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-blue">
                <h1>Periodos</h1>
                <a href="/periodos/add">Novo período</a>
            </header>
    
            <div class="w3-container">
                <table class="w3-table-all">
                    <tr>
                        <th>Nome</th>
                    </tr>
    `

    for (let i = 0; i < list.length; i++) {
        pagHTML += `
        <tr>
            <td>
                <a href="/periodos/${list[i].nome}">
                    ${list[i].nome}
                </a>
            </td>
        </tr>
        `
    }

    pagHTML += `
    </table>
    </div>
        <footer class="w3-container w3-blue">
            <h5>Generated by RPCW2023 in ${d} - [<a href="/">Voltar à página inicial</a>]</h5>
        </footer>
    </div>
    </body>
    </html>
    `
    return pagHTML
}

exports.paginaPeriodo = function (periodo, compositores) {
    pagHTML = `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
        <title>Período ${periodo}</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-blue">
                <h1>Período ${periodo}</h1>
            </header>
    
            <div class="w3-container">
            <p>Compositores deste período:</p>
                <ol>
    `
    for (let i = 0; i < compositores.length; i++) {
        pagHTML += `
                        <li>
                            <a href="/compositores/${compositores[i].id}">
                                ${compositores[i].nome}
                            </a>
                        </li>
        `
    }

    pagHTML += `
        </ol>
        </div>
        <footer class="w3-container w3-blue">
            <h5>Generated by RPCW2023 - [<a href="/periodos">Voltar à lista de períodos</a>]</h5>
        </footer>
        </div>
        </body>
        </html>
        `
    return pagHTML


}

exports.adicionarPeriodo = function (d) {
    return `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
        <title>Novo Período</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-blue">
                <h1>Novo Período</h1>
            </header>
    
            <div class="w3-container">
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Dados do novo Período</legend>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                    <fieldset/>
                    <br>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Registar novo período</button>
                </form>
            </div>
            <footer class="w3-container w3-blue">
                <h5>Generated by RPCW2023 in ${d} - [<a href="/periodos">Voltar à lista de períodos</a>]</h5>
            </footer>
        </div>
    </body>
    </html>
    `
}

exports.errorPage = function (errorMessage, d) {
    return `
    <h1>${d}: Error: ${errorMessage}</h1>
    `
}